// lib/screens/create_group_screen.dart
import 'package:flutter/material.dart';
import '../models/chicken.dart' as chicken;
import '../models/fish.dart' as fish;
import '../models/pig.dart' as pig;
import '../services/chicken_service.dart';
import '../services/fish_service.dart';
import '../services/pig_service.dart';
import '../models/food_consumption.dart';
import '../widgets/loading_widget.dart';

class CreateGroupScreen extends StatefulWidget {
  final String livestockType;

  CreateGroupScreen({required this.livestockType});

  @override
  _CreateGroupScreenState createState() => _CreateGroupScreenState();
}

class _CreateGroupScreenState extends State<CreateGroupScreen> {
  final _formKey = GlobalKey<FormState>();
  final ChickenService _chickenService = ChickenService();
  final FishService _fishService = FishService();
  final PigService _pigService = PigService();

  String _name = '';
  int _totalCount = 0;
  DateTime _birthDate = DateTime.now();
  String _fishType = 'Kanga';  // Default fish type
  String _pigType = 'petit';   // Default pig type

  // Future<void> _createGroup() async {
  //   if (_formKey.currentState!.validate()) {
  //     _formKey.currentState!.save();

  //     try {
  //       if (widget.livestockType == 'Poulets') {
  //         chicken.Chicken newGroup = chicken.Chicken(
  //           id: '',  // ID will be generated by the backend
  //           title: _name,
  //           totalCount: _totalCount,
  //           birthDate: _birthDate,
  //           createdAt: DateTime.now(),
  //           modifiedAt: DateTime.now(),
  //         );
  //         await _chickenService.createChickenGroup(newGroup);
  //       } else if (widget.livestockType == 'Poissons') {
  //         fish.Fish newGroup = fish.Fish(
  //           id: '',  // ID will be generated by the backend
  //           name: _name,
  //           totalCount: _totalCount,
  //           type: _fishType,
  //           birthDate: _birthDate,
  //           createdAt: DateTime.now(),
  //           modifiedAt: DateTime.now(),
  //         );
  //         await _fishService.createFishGroup(newGroup);
  //       } else if (widget.livestockType == 'Porcs') {
  //         pig.Pig newGroup = pig.Pig(
  //           id: '',  // ID will be generated by the backend
  //           name: _name,
  //           totalCount: _totalCount,
  //           type: _pigType,
  //           birthDate: _birthDate,
  //           createdAt: DateTime.now(),
  //           modifiedAt: DateTime.now(),
  //         );
  //         await _pigService.createPigGroup(newGroup);
  //       }

  //       ScaffoldMessenger.of(context).showSnackBar(
  //         SnackBar(content: Text('Groupe créé avec succès')),
  //       );

  //       Navigator.pop(context, true);
  //     } catch (e) {
  //       print('Erreur lors de la création du groupe: $e');
  //       ScaffoldMessenger.of(context).showSnackBar(
  //         SnackBar(content: Text('Erreur lors de la création du groupe: $e')),
  //       );
  //     }
  //   }
  // }

  Future<void> _createGroup() async {
    if (_formKey.currentState!.validate()) {
      _formKey.currentState!.save();

      // Show loading dialog
      showDialog(
        context: context,
        barrierDismissible: false,
        builder: (BuildContext context) {
          return Dialog(
            backgroundColor: Colors.transparent,
            child: Container(
              width: MediaQuery.of(context).size.width * 0.8,
              height: MediaQuery.of(context).size.height * 0.3,
              padding: EdgeInsets.all(16.0),
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(10),
              ),
              child: Center(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    CircularProgressIndicator(),
                    SizedBox(height: 16),
                    Text("Création en cours", style: TextStyle(fontSize: 18)),
                    SizedBox(height: 8),
                    Text("Veuillez patienter...", style: TextStyle(fontSize: 16, color: Colors.grey)),
                  ],
                ),
              ),
            ),
          );
        },
      );

      try {
        if (widget.livestockType == 'Poulets') {
          chicken.Chicken newGroup = chicken.Chicken(
            id: '',
            title: _name,
            totalCount: _totalCount,
            birthDate: _birthDate,
            createdAt: DateTime.now(),
            modifiedAt: DateTime.now(),
          );
          await _chickenService.createChickenGroup(newGroup);
        } else if (widget.livestockType == 'Poissons') {
          fish.Fish newGroup = fish.Fish(
            id: '',
            name: _name,
            totalCount: _totalCount,
            type: _fishType,
            birthDate: _birthDate,
            createdAt: DateTime.now(),
            modifiedAt: DateTime.now(),
          );
          await _fishService.createFishGroup(newGroup);
        } else if (widget.livestockType == 'Porcs') {
          pig.Pig newGroup = pig.Pig(
            id: '',
            name: _name,
            totalCount: _totalCount,
            type: _pigType,
            birthDate: _birthDate,
            createdAt: DateTime.now(),
            modifiedAt: DateTime.now(),
          );
          await _pigService.createPigGroup(newGroup);
        }

        Navigator.pop(context); // Close the loading dialog
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Groupe créé avec succès')),
        );

        Navigator.pop(context, true); // Navigate back
      } catch (e) {
        Navigator.pop(context); // Close the loading dialog
        print('Erreur lors de la création du groupe: $e');
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Erreur lors de la création du groupe: $e')),
        );
      }
    }
  }

  Future<void> _selectBirthDate(BuildContext context) async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: _birthDate,
      firstDate: DateTime(2000),
      lastDate: DateTime.now(),
    );
    if (picked != null && picked != _birthDate) {
      setState(() {
        _birthDate = picked;
        print('Date de naissance sélectionnée: $_birthDate'); // Debug statement
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          'Créer un groupe de ${widget.livestockType}',
          style: TextStyle(
            color: Colors.white,
            fontSize: 20,
            fontWeight: FontWeight.bold,
          ),
        ),
        backgroundColor: Color(0xFF285429),
        centerTitle: true,
        iconTheme: IconThemeData(color: Colors.white),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(18.0),
        child: Form(
          key: _formKey,
          autovalidateMode: AutovalidateMode.disabled,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              _buildInputField(
                label: 'Nom',
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Veuillez entrer un nom';
                  }
                  return null;
                },
                onSaved: (value) {
                  _name = value!;
                },
              ),
              SizedBox(height: 20),
              _buildInputField(
                label: 'Nombre total',
                keyboardType: TextInputType.number,
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Veuillez entrer un nombre total';
                  }
                  return null;
                },
                onSaved: (value) {
                  _totalCount = int.parse(value!);
                },
              ),
              SizedBox(height: 20),
              if (widget.livestockType == 'Poissons')
                _buildDropdownField(
                  label: 'Type de poisson',
                  value: _fishType,
                  items: ['Kanga', 'Cellule'],
                  onChanged: (String? newValue) {
                    setState(() {
                      _fishType = newValue!;
                    });
                  },
                ),
              if (widget.livestockType == 'Porcs')
                // _buildDropdownField(
                //   label: 'Type de porc',
                //   value: _pigType,
                //   items: ['petit', 'moyen', 'grand'],
                //   onChanged: (String? newValue) {
                //     setState(() {
                //       _pigType = newValue!;
                //     });
                //   },
                // ),
              SizedBox(height: 20),
              ListTile(
                contentPadding: EdgeInsets.symmetric(horizontal: 0),
                title: Row(
                  children: [
                    Text(
                      "Date de naissance: ",
                      style: TextStyle(color: Color(0xFF285429)),
                    ),
                    Text(
                      "${_birthDate.toLocal()}".split(' ')[0],
                      style: TextStyle(fontWeight: FontWeight.bold, color: Color(0xFF285429)),
                    ),
                  ],
                ),
                trailing: Icon(Icons.calendar_today, color: Color(0xFF285429)),
                onTap: () => _selectBirthDate(context),
              ),
              SizedBox(height: 20),
              Center(
                child: ElevatedButton(
                  onPressed: _createGroup,
                  child: Text('Créer le groupe'),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Color(0xFF285429),
                    padding: EdgeInsets.symmetric(horizontal: 30, vertical: 15),
                    textStyle: TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: Colors.white),
                    foregroundColor : Colors.white
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildInputField({
    required String label,
    TextInputType keyboardType = TextInputType.text,
    required FormFieldValidator<String> validator,
    required FormFieldSetter<String> onSaved,
  }) {
    return TextFormField(
      decoration: InputDecoration(
        labelText: label,
        labelStyle: TextStyle(color: Color(0xFF285429)),
        focusedBorder: OutlineInputBorder(
          borderSide: BorderSide(color: Color(0xFF285429)),
          borderRadius: BorderRadius.circular(10),
        ),
        enabledBorder: OutlineInputBorder(
          borderSide: BorderSide(color: Color(0xFF285429)),
          borderRadius: BorderRadius.circular(10),
        ),
      ),
      keyboardType: keyboardType,
      validator: validator,
      onSaved: onSaved,
    );
  }

  Widget _buildDropdownField({
    required String label,
    required String value,
    required List<String> items,
    required ValueChanged<String?> onChanged,
  }) {
    return DropdownButtonFormField<String>(
      value: value,
      decoration: InputDecoration(
        labelText: label,
        labelStyle: TextStyle(color: Color(0xFF285429)),
        focusedBorder: OutlineInputBorder(
          borderSide: BorderSide(color: Color(0xFF285429)),
          borderRadius: BorderRadius.circular(10),
        ),
        enabledBorder: OutlineInputBorder(
          borderSide: BorderSide(color: Color(0xFF285429)),
          borderRadius: BorderRadius.circular(10),
        ),
      ),
      items: items.map((String type) {
        return DropdownMenuItem<String>(
          value: type,
          child: Text(type),
        );
      }).toList(),
      onChanged: onChanged,
    );
  }
}